### ISSUE TITLE
Alphabetize lead facilitators in "Filter by Facilitator" select

### ISSUE THREAD

**Issue by amygroshek** [lougroshek/block_questionreport#12]
Options on the "Filter by Facilitator" select are not fully alphabetized. Please alphabetize by last and then first name.
<img width="431" alt="Screen Shot 2021-03-13 at 12 01 56 PM" src="https://user-images.githubusercontent.com/746182/111039511-0e4b3200-83f4-11eb-8ed9-ec211199583a.png">

**Comment by shediac2** [comment]
This has been corrected.

**Comment by amygroshek** [comment]
Hi @shediac2,

I still see some entries at the end that are not alphabetized. It looks like current facilitators are at the end and not alphabetized.
<img width="1022" alt="Screen Shot 2021-03-13 at 2 50 49 PM" src="https://user-images.githubusercontent.com/746182/111044007-95f06b00-840b-11eb-9bdb-8855e9fda2d3.png">

**Comment by shediac2** [comment]
You are too fast - let me apply this to site ...

**Comment by amygroshek** [comment]
It looks like they are alphabetized by first name. Can we alphabetize them by last and then first? At least by last name?

**Comment by shediac2** [comment]
Its bit of work to do this. The reason being is that these names are combined from the non moodle courses and the names are not not broken up to be able to sort on, and also they are merged with the names from the moodle courses. Can we defer this until later?

**Comment by amygroshek** [comment]
👍🏻 Happy to defer this. I'll leave open.
