### ISSUE TITLE
Remove "Diagnostic Survey" option from charts, since we have no charts for that survey

### ISSUE THREAD

**Issue by amygroshek** [lougroshek/block_questionreport#14]
https://learning.teachinglab.org/blocks/questionreport/charts.php?action=view&cid=M-239

<img width="1051" alt="Screen Shot 2021-03-13 at 12 08 54 PM" src="https://user-images.githubusercontent.com/746182/111039686-f2945b80-83f4-11eb-899a-5393ba2f0a97.png">

**Comment by shediac2** [comment]
This has been corrected.

**Comment by amygroshek** [comment]
I still see this issue on the live site. 
<img width="1373" alt="Screen Shot 2021-03-13 at 2 53 02 PM" src="https://user-images.githubusercontent.com/746182/111044044-d64fe900-840b-11eb-990c-969e6a0fc8c6.png">

**Comment by amygroshek** [comment]
Looks good!
